# Generated by Django 4.1 on 2022-12-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('colorProducto', models.CharField(max_length=20)),
                ('dimesionesProducto', models.CharField(max_length=15)),
                ('pesoProducto', models.CharField(max_length=6)),
                ('marcaProducto', models.CharField(max_length=6)),
            ],
        ),
    ]
