# Generated by Django 4.1 on 2022-12-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_producto_ubicacion_alter_producto_marcaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
